#!/usr/bin/env bash


if [ "$(id -u)" != "0" ]
then
	echo "Sorry, you are not root."
	exit 1
fi

GIT_CLONE_WRAPPER="gclone"

APP_PATH="/opt/gclone"
BIN_PATH="/usr/local/bin"

echo -e "Installing.."

mkdir -p "${APP_PATH}"

cp "${GIT_CLONE_WRAPPER}.sh" "${APP_PATH}/${GIT_CLONE_WRAPPER}"

chmod +x "${APP_PATH}/${GIT_CLONE_WRAPPER}"

ln -s "${APP_PATH}/${GIT_CLONE_WRAPPER}" "${BIN_PATH}/${GIT_CLONE_WRAPPER}"

echo -e "All set."